# Generated by Django 5.1.4 on 2025-01-20 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temp_inherit_app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='stubranch',
            field=models.CharField(default='not available', max_length=10),
        ),
    ]
