# Generated by Django 5.1.4 on 2025-01-24 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temp_inherit_app1', '0002_student_stubranch'),
    ]

    operations = [
        migrations.CreateModel(
            name='User1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=15)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
    ]
